services:
  db:
    build: ./Database
    ports:
      - "14330:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "n5m_35z3m_A_73137"
      MSSQL_PID: "Express"
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  backend:
    build: ./Backend/BidVerse_backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:8081/health || exit 1"]
      interval: 50s
      timeout: 15s
      retries: 3
      start_period: 40s
  flask-ai:
    build: ./AI_Flask
    ports:
      - "5000:5000"
    depends_on:
      - backend
  react-frontend:
    build: ./Frontend/my-vite-app
    ports:
      - "80:80"
    depends_on:
      - backend